version: "2"

linters:
  # Disable all linters by default, then enable individual linters explicitly.
  default: none
  enable:
    # Enable the ones that are by default.
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Add some additional linters
    - misspell
    - prealloc
    - revive
    - unconvert

formatters:
  enable:
    - goimports

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s. Default is 0 (disabled).
  timeout: 3m
