before:
  hooks:
    - 'go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest'
    - 'goversioninfo
      -platform-specific
      -ver-major="{{ .Major }}" -product-ver-major="{{ .Major }}"
      -ver-minor="{{ .Minor }}" -product-ver-minor="{{ .Minor }}"
      -ver-patch="{{ .Patch }}" -product-ver-patch="{{ .Patch }}"
      -file-version="{{ .Version }}+{{ .FullCommit }}" -product-version="{{ .Version }}+{{ .FullCommit }}"'

builds:
- binary: npiperelay
  goos:
    - windows
  goarch:
    - 386
    - amd64

archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  extra_files:
    - glob: "./dist/{{ .ProjectName }}_windows_386/{{ .ProjectName }}.exe"
      name_template: "{{ .ProjectName }}_windows_386/{{ .ProjectName }}.exe"
    - glob: "./dist/{{ .ProjectName }}_windows_amd64_v1/{{ .ProjectName }}.exe"
      name_template: "{{ .ProjectName }}_windows_amd64_v1/{{ .ProjectName }}.exe"

changelog:
  sort: asc
