name: goreleaser

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-go
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - id: goreleaser
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GOVERSION: ${{ steps.setup-go.outputs.go-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}